// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF3geu92b5deYaQqjftpQqgIeSq5BBdPU',
    appId: '1:404095667798:web:a13f5473640bfff55275f7',
    messagingSenderId: '404095667798',
    projectId: 'doctor-hunt-138ba',
    authDomain: 'doctor-hunt-138ba.firebaseapp.com',
    storageBucket: 'doctor-hunt-138ba.firebasestorage.app',
    measurementId: 'G-R4T88T0FM0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEKQ8CsPTVJeddXNjxKu2yE4UYxjQl1BE',
    appId: '1:404095667798:android:7ecfd687726431e45275f7',
    messagingSenderId: '404095667798',
    projectId: 'doctor-hunt-138ba',
    storageBucket: 'doctor-hunt-138ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcZlEGDqxqiifMcY36b72xDd0gDorsSr8',
    appId: '1:404095667798:ios:07a57af9836243985275f7',
    messagingSenderId: '404095667798',
    projectId: 'doctor-hunt-138ba',
    storageBucket: 'doctor-hunt-138ba.firebasestorage.app',
    iosBundleId: 'com.example.doctorHunt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcZlEGDqxqiifMcY36b72xDd0gDorsSr8',
    appId: '1:404095667798:ios:07a57af9836243985275f7',
    messagingSenderId: '404095667798',
    projectId: 'doctor-hunt-138ba',
    storageBucket: 'doctor-hunt-138ba.firebasestorage.app',
    iosBundleId: 'com.example.doctorHunt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCF3geu92b5deYaQqjftpQqgIeSq5BBdPU',
    appId: '1:404095667798:web:8c27ee06399e600c5275f7',
    messagingSenderId: '404095667798',
    projectId: 'doctor-hunt-138ba',
    authDomain: 'doctor-hunt-138ba.firebaseapp.com',
    storageBucket: 'doctor-hunt-138ba.firebasestorage.app',
    measurementId: 'G-VK8L5JQL1M',
  );
}
